# Environment Settings
gpu_id: 0

# Model Settings
n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.2
hidden_act: gelu
layer_norm_eps: 1.e-12
initializer_range: 0.02
loss_type: CE
weight_decay: 0

# Data settings
MAX_ITEM_LIST_LENGTH: 20
  
# Training Settings
train_batch_size: 512
neg_sampling: null
num_prior: 3
pretrain_epoch: 50
lamb: 1.2
alpha: 0.5
stopping_step: 10
show_pretrain_progress: False
pretrain_only: False
